-- Auto-generated by map_assets.js
-- Maps cocktail video files to their database records
-- Run this in Supabase SQL Editor

UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/aperol-spritz-italian-summer-evening.mp4' WHERE slug = 'aperol-spritz-italian-summer-evening';
UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/blue-lagoon-futuristic-ocean-bar.mp4' WHERE slug = 'blue-lagoon-futuristic-ocean-bar';
UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/cosmopolitan-luxury-hotel-bar.mp4' WHERE slug = 'cosmopolitan-luxury-hotel-bar';
UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/dark-and-stormy-storm-watching-deck.mp4' WHERE slug = 'dark-and-stormy-storm-watching-deck';
UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/espresso-martini-midnight-work-session.mp4' WHERE slug = 'espresso-martini-midnight-work-session';
UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/gin-and-tonic-botanical-conservatory.mp4' WHERE slug = 'gin-and-tonic-botanical-conservatory';
UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/long-island-iced-tea-house-party.mp4' WHERE slug = 'long-island-iced-tea-house-party';
UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/mai-tai-tiki-paradise.mp4' WHERE slug = 'mai-tai-tiki-paradise';
UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/margarita-neon-rooftop-party.mp4' WHERE slug = 'margarita-neon-rooftop-party';
UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/martini-james-bond-night.mp4' WHERE slug = 'martini-james-bond-night';
UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/mimosa-luxury-brunch.mp4' WHERE slug = 'mimosa-luxury-brunch';
UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/mojito-tropical-escape.mp4' WHERE slug = 'mojito-tropical-escape';
UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/moscow-mule-winter-cabin.mp4' WHERE slug = 'moscow-mule-winter-cabin';
UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/old-fashioned-gentlemans-club.mp4' WHERE slug = 'old-fashioned-gentlemans-club';
UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/paloma-desert-sunset.mp4' WHERE slug = 'paloma-desert-sunset';
UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/passion-fruit-martini-dubai-sky-lounge.mp4' WHERE slug = 'passion-fruit-martini-dubai-sky-lounge';
UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/pina-colada-maldives-resort.mp4' WHERE slug = 'pina-colada-maldives-resort';
UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/sangria-spanish-courtyard.mp4' WHERE slug = 'sangria-spanish-courtyard';
UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/strawberry-daiquiri-spring-garden.mp4' WHERE slug = 'strawberry-daiquiri-spring-garden';
UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/whiskey-sour-rainy-luxury-lounge.mp4' WHERE slug = 'whiskey-sour-rainy-luxury-lounge';
