/**
 * map_assets.js
 * 
 * Copies cocktail videos from cocktail_videos/ into public/assets/videos/
 * with clean, URL-safe filenames and generates a SQL UPDATE script to set
 * backdrop_video_url on the matching cocktails in Supabase.
 * 
 * Also copies cocktail images from cocktail_images/ into public/assets/images/
 * with clean names and generates backdrop_image_url UPDATEs.
 *
 * Run:  node scripts/map_assets.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const VIDEOS_SRC = path.join(ROOT, 'cocktail_videos');
const IMAGES_SRC = path.join(ROOT, 'cocktail_images');
const VIDEOS_DST = path.join(ROOT, 'public', 'assets', 'videos');
const IMAGES_DST = path.join(ROOT, 'public', 'assets', 'images');

// Ensure destination dirs exist
fs.mkdirSync(VIDEOS_DST, { recursive: true });
fs.mkdirSync(IMAGES_DST, { recursive: true });

// ─── Cocktail slugs from our data ─────────────────────────────
const cocktailsData = JSON.parse(
  fs.readFileSync(path.join(ROOT, 'data', 'cocktails.json'), 'utf8')
);

// ─── Video → Cocktail name mapping (from filenames) ───────────
const videoMap = {
  'Mojito': 'mojito-tropical-escape',
  'Whiskey_Sour': 'whiskey-sour-rainy-luxury-lounge',
  'Margarita': 'margarita-neon-rooftop-party',
  'Cosmopolitan': 'cosmopolitan-luxury-hotel-bar',
  'Old_Fashioned': 'old-fashioned-gentlemans-club',
  'Piña_Colada': 'pina-colada-maldives-resort',
  'Espresso_Martini': 'espresso-martini-midnight-work-session',
  'Aperol_Spritz': 'aperol-spritz-italian-summer-evening',
  'Blue_Lagoon': 'blue-lagoon-futuristic-ocean-bar',
  'Strawberry_Daiquiri': 'strawberry-daiquiri-spring-garden',
  'Mai_Tai': 'mai-tai-tiki-paradise',
  'Long_Island': 'long-island-iced-tea-house-party',
  'Martini_moonlit': 'martini-james-bond-night',
  'Sangria': 'sangria-spanish-courtyard',
  'Moscow_Mule': 'moscow-mule-winter-cabin',
  'Paloma': 'paloma-desert-sunset',
  'Mimosa': 'mimosa-luxury-brunch',
  'Gin_Tonic': 'gin-and-tonic-botanical-conservatory',
  'Dark_Stormy': 'dark-and-stormy-storm-watching-deck',
  'Passion_Fruit': 'passion-fruit-martini-dubai-sky-lounge',
};

// Map video file prefix → cocktail slug from the database
function findCocktailSlug(videoFilename) {
  for (const [prefix, slug] of Object.entries(videoMap)) {
    if (videoFilename.startsWith(prefix)) {
      // Find the matching cocktail slug in data to verify it exists
      const match = cocktailsData.find(c => c.slug === slug);
      if (match) return match.slug;
    }
  }
  return null;
}

// ─── Process Videos ───────────────────────────────────────────
console.log('=== Processing Videos ===\n');
const sqlStatements = [];

const videoFiles = fs.readdirSync(VIDEOS_SRC).filter(f => f.endsWith('.mp4'));
for (const file of videoFiles) {
  const slug = findCocktailSlug(file);
  if (!slug) {
    console.log(`⚠️  No match for video: ${file}`);
    continue;
  }

  // Clean filename: slug-based
  const cleanName = `${slug}.mp4`;
  const src = path.join(VIDEOS_SRC, file);
  const dst = path.join(VIDEOS_DST, cleanName);

  fs.copyFileSync(src, dst);
  const sizeKB = Math.round(fs.statSync(dst).size / 1024);
  console.log(`✅ ${file} → ${cleanName} (${sizeKB} KB) → slug: ${slug}`);

  sqlStatements.push(
    `UPDATE public.cocktails SET backdrop_video_url = '/assets/videos/${cleanName}' WHERE slug = '${slug}';`
  );
}

// ─── Process Images ───────────────────────────────────────────
// The images have Gemini-generated random names, so we'll just
// copy them all and assign them in order to cocktails that don't
// have a backdrop_image_url. We'll name them by index for now,
// and also copy the rocks-glass image separately.

console.log('\n=== Processing Images ===\n');

if (fs.existsSync(IMAGES_SRC)) {
  const imageFiles = fs.readdirSync(IMAGES_SRC)
    .filter(f => f.endsWith('.png') && !f.startsWith('.'));

  // Copy all images with sequential clean names
  imageFiles.forEach((file, index) => {
    const cleanName = file.startsWith('rocks-glass') 
      ? 'rocks-glass.png' 
      : `cocktail-image-${String(index + 1).padStart(2, '0')}.png`;
    
    const src = path.join(IMAGES_SRC, file);
    const dst = path.join(IMAGES_DST, cleanName);

    fs.copyFileSync(src, dst);
    const sizeMB = (fs.statSync(dst).size / (1024 * 1024)).toFixed(1);
    console.log(`✅ ${file} → ${cleanName} (${sizeMB} MB)`);
  });
} else {
  console.log(`⚠️ Source images directory ${IMAGES_SRC} not found. Skipping image copying.`);
}

// ─── Generate SQL file ────────────────────────────────────────
const sqlContent = `-- Auto-generated by map_assets.js
-- Maps cocktail video files to their database records
-- Run this in Supabase SQL Editor

${sqlStatements.join('\n')}
`;

const sqlPath = path.join(ROOT, 'update_media_urls.sql');
fs.writeFileSync(sqlPath, sqlContent);
console.log(`\n📝 Generated SQL file: update_media_urls.sql`);
console.log(`   Contains ${sqlStatements.length} UPDATE statements`);

// ─── Also update cocktails.json with video URLs ───────────────
for (const cocktail of cocktailsData) {
  const videoFile = `${cocktail.slug}.mp4`;
  const videoPath = path.join(VIDEOS_DST, videoFile);
  if (fs.existsSync(videoPath)) {
    cocktail.backdrop_video_url = `/assets/videos/${videoFile}`;
  }
}

const jsonPath = path.join(ROOT, 'data', 'cocktails.json');
fs.writeFileSync(jsonPath, JSON.stringify(cocktailsData, null, 2) + '\n');
console.log('📝 Updated data/cocktails.json with video URLs');
